from negotiationarena.agents.chatgpt import ChatGPTAgent
from negotiationarena.constants import (
    MONEY_TOKEN,
    AGENT_ONE,
    AGENT_TWO,
    PLAYER_ANSWER_TAG,
    PROPOSED_TRADE_TAG,
    PROPOSAL_COUNT_TAG,
    RESOURCES_TAG,
    GOALS_TAG,
    REASONING_TAG,
    MESSAGE_TAG,
)


class FixedFirstOfferSellerAgent(ChatGPTAgent):
    """
    A ChatGPTAgent whose opening offer is fixed by the experimenter instead
    of generated by the model, so the negotiation's starting anchor is
    controlled directly. Only the very first `chat()` call is scripted (no
    API call is made for it); every later call is a normal API call, so the
    seller's strategy from its second move onward is still the model's own.
    """

    def __init__(
        self, first_offer, resource_name="X", resource_amount=1, **kwargs
    ):
        super().__init__(**kwargs)
        self.first_offer = first_offer
        self.resource_name = resource_name
        self.resource_amount = resource_amount
        self.used_scripted_offer = False

    def chat(self):
        if not self.used_scripted_offer:
            self.used_scripted_offer = True
            return self._scripted_first_offer()
        return super().chat()

    def _scripted_first_offer(self):
        return (
            f"<{PROPOSAL_COUNT_TAG}> 1 </{PROPOSAL_COUNT_TAG}>\n"
            f"<{RESOURCES_TAG}> {self.resource_name}: {self.resource_amount} </{RESOURCES_TAG}>\n"
            f"<{GOALS_TAG}> [scripted opening offer, not generated by the model] </{GOALS_TAG}>\n"
            f"<{REASONING_TAG}> Opening offer fixed by experiment design "
            f"(FixedFirstOfferSellerAgent); not generated by the model. </{REASONING_TAG}>\n"
            f"<{PLAYER_ANSWER_TAG}> PROPOSAL </{PLAYER_ANSWER_TAG}>\n"
            f"<{PROPOSED_TRADE_TAG}> {AGENT_ONE} Gives {self.resource_name}: {self.resource_amount} | "
            f"{AGENT_TWO} Gives {MONEY_TOKEN}: {self.first_offer} </{PROPOSED_TRADE_TAG}>\n"
            f"<{MESSAGE_TAG}> I am offering the object for {self.first_offer} {MONEY_TOKEN}. </{MESSAGE_TAG}>"
        )
